roclark/sportsipy

- sportsreference/mlb/boxscore.py
- sportsreference/mlb/constants.py
- sportsreference/nba/boxscore.py
- sportsreference/ncaab/boxscore.py
- sportsreference/nfl/boxscore.py
- sportsreference/nfl/constants.py
- sportsreference/nhl/boxscore.py
- sportsreference/nhl/constants.py
- tests/unit/test_mlb_boxscore.py
- tests/unit/test_nba_boxscore.py
- tests/unit/test_ncaab_boxscore.py
- tests/unit/test_nfl_boxscore.py
- tests/unit/test_nhl_boxscore.py
Now able to more accurately parse historic game information when less data is displayed on a boxscore page.
Fixes #5.
> Fix game info parsing

- sportsreference/ncaab/constants.py
sports-reference.com changed the layout of the NCAAB rankings page which prevented any rankings from being properly parsed and saved in the Rankings class. They still have an old version which is accessible by appending '-old' to the URL. Targetting this new page allows the original rankings logic to be used without making any changes.
Fixes #13
> Fix issue pulling NCAAB rankings

- docs/nfl.rst
An example in the NFL documentation was incorrect as it used a different
set of parameters than what is actually expected.
> Fix issue with NFL documentation

- sportsreference/mlb/roster.py
- sportsreference/nba/roster.py
- sportsreference/ncaab/roster.py
- sportsreference/ncaaf/roster.py
- sportsreference/nfl/roster.py
- sportsreference/nhl/roster.py
- sportsreference/utils.py
- tests/unit/test_ncaab_roster.py
The Roster class currently throws an error whenever a player doesn't have any stats associated with him/her because it can't parse a table that doesn't exist. Now, the code will attempt to parse as much information as possible and store it in the class properties.
Fixes #29
> Fix issue pulling stats from blank players

- sportsreference/ncaaf/boxscore.py
- tests/unit/test_ncaaf_boxscore.py
sports-reference.com changed the layout of the Boxscores page which stored information in incorrect properties. To overcome the issue of sports-reference.com changing the layout of the Boxscores page again in the future, a more generic, yet robust parsing scheme is needed to persistently capture the desired information.
Fixes #47
> Update NCAAF Boxscore meta information parsing

- sportsreference/mlb/roster.py
- sportsreference/nba/roster.py
- sportsreference/ncaab/roster.py
- sportsreference/ncaaf/roster.py
- sportsreference/nfl/roster.py
- sportsreference/nhl/roster.py
- tests/integration/roster/test_mlb_roster.py
- tests/integration/roster/test_nba_roster.py
- tests/integration/roster/test_ncaab_roster.py
- tests/integration/roster/test_ncaaf_roster.py
- tests/integration/roster/test_nfl_roster.py
- tests/integration/roster/test_nhl_roster.py
A new slim parameter should be added to the Roster class if the desire is to just get the names and/or player ID's of each player on a team. This short-circuits the call to the Player class which eliminates the need for a 2-3 second instantiation and call to the individual player's stats page. This allows the names and IDs to be returned in a small fraction of the time compared to the standard request.
Fixes #26
> Create slim parameter for Roster class

- tests/integration/roster/test_nfl_roster.py
- tests/integration/roster/test_nhl_roster.py
- tests/integration/schedule/test_mlb_schedule.py
- tests/integration/schedule/test_nba_schedule.py
- tests/integration/schedule/test_ncaab_schedule.py
- tests/integration/schedule/test_ncaaf_schedule.py
- tests/integration/schedule/test_nfl_schedule.py
- tests/integration/schedule/test_nhl_schedule.py
Many of the integration tests were getting stuck while either trying to pull from the external network (which should be avoided) or re-pulling information that was unnecessary for a given test. This would cause some tests to takeas long as two minutes while trying to pull all of the desired information when they should be taking a couple seconds or less. The new updates test all of the same code, but go about it in a smarter
way to reduce the testing time by 66%.
> Improve integration test performance

- .travis.yml
- requirements.txt
- setup.py
With Python 3.4 officially reaching end-of-life on March 16, 2019, support should be dropped from `sportsreference` to encourage users to transition to a newer version of Python.
> Drop Python 3.4 support

- sportsreference/ncaab/teams.py
- tests/unit/test_ncaab_teams.py
Prior to the 2009 season, sports-reference.com contained less data for each NCAAB team. Any fields that were missing that require mathematical operations (such as the subtraction in `defensive_rebounds`, `opp_defensive_rebounds`, and `net_rating`), if at least one of the fields is empty, the command will throw an error. To combat this behavior, we need to pre-emptively catch any arithmetic errors and return a default value.
Fixes #68 
> Fix issue pulling historical NCAAB fields

- sportsreference/nba/schedule.py
Iterating through an NBA team's schedule right before the playoffs begin can throw an error for participating teams as basketball-reference.com uses a link similar to one being used to identify playoff games in sportsreference. By directly checking for the ID tag used in the playoff table, we can cleanly pull the NBA table if applicable.
Fixes #72
> Fix issue pulling NBA playoff games

- sportsreference/nhl/roster.py
The NHL team rosters were throwing errors for certain teams when the website only uses uppercase team abbreviations, like with the Vegas Golen Knights. Forcing abbreviations to be uppercase resolves this issue.
Fixes #99
> Fix issue pulling NHL rosters

- sportsreference/nba/schedule.py
- tests/integration/schedule/test_nba_schedule.py
The NBA playoff schedules should include a binary indicator which can be used to identify if a game was played during the playoffs or the regular season.
Fixes #78
> Add playoff indicator to NBA schedules

- sportsreference/ncaab/boxscore.py
For any NCAAB post-season match, the Boxscores class would fail to pull the correct home team's name as it falsely claimed the final table descriptor as the home team's name, when it actually is dedicated to information on the specific playoff game, such as 'Big Ten Conf Tournament - Final'.
Fixes #77
> Fix issue getting home names in NCAAB playoffs

- tests/unit/test_mlb_boxscore.py
The MLB unit tests were not properly throwing an `HTTPError`, causing the test to fail. The requests have now been properly mocked and `HTTPErrors` are thrown as expected.
> Fix issue with MLB tests

- .gitignore
- tests/integration/boxscore/test_mlb_boxscore.py
- tests/integration/boxscore/test_nba_boxscore.py
- tests/integration/boxscore/test_ncaab_boxscore.py
- tests/integration/boxscore/test_ncaaf_boxscore.py
- tests/integration/boxscore/test_nfl_boxscore.py
- tests/integration/boxscore/test_nhl_boxscore.py
- tests/integration/conferences/test_ncaab_conferences.py
- tests/integration/conferences/test_ncaaf_conferences.py
- tests/integration/rankings/test_ncaab_rankings.py
- tests/integration/rankings/test_ncaaf_rankings.py
- tests/integration/roster/test_mlb_roster.py
- tests/integration/roster/test_nba_roster.py
- tests/integration/roster/test_ncaab_roster.py
- tests/integration/roster/test_ncaaf_roster.py
- tests/integration/roster/test_nfl_roster.py
- tests/integration/roster/test_nhl_roster.py
- tests/integration/schedule/test_mlb_schedule.py
- tests/integration/schedule/test_nba_schedule.py
- tests/integration/schedule/test_ncaab_schedule.py
- tests/integration/schedule/test_ncaaf_schedule.py
- tests/integration/schedule/test_nfl_schedule.py
- tests/integration/schedule/test_nhl_schedule.py
- tests/integration/teams/test_mlb_integration.py
- tests/integration/teams/test_nba_integration.py
- tests/integration/teams/test_ncaab_integration.py
- tests/integration/teams/test_ncaaf_integration.py
- tests/integration/teams/test_nfl_integration.py
- tests/integration/teams/test_nhl_integration.py
In some cases (such as running tests in Visual Studio Code), the "open" function in Python uses the incorrect file encoding format which can cause errors. To combat this, the encoding format should be explicitly stated.
> Force UTF-8 encoding for opening test files

- sportsreference/ncaaf/roster.py
- tests/unit/test_ncaaf_roster.py
While attempting to pull player information for players from several seasons ago (tested on 2000 and earlier), sports-reference.com doesn't always contain the player's weight. In this case, their weight will still be set as `None`, causing an `AttributeError` to be thrown while attempting to replace the contents of what it expects to be a string. If this situation occurs, the weight should stay as `None` for the end-user to decide how they want to handle the omission.
Fixes #141
> Fix issue pulling weight of older NCAAF players

- sportsreference/ncaaf/schedule.py
In the seasons prior to 2013, sports-reference.com does not include a time field in the NCAAF game's information page. This causes the time property to be set to `None`, which fails while attempting to parse a `DateTime` between the date and time properties. This behavior can be circumvented by only creating a DateTime of the date as opposed to the date and time when time is `None`.
Fixes #138
> Fix issue pulling NCAAF games without time

- .travis.yml
Code coverage should be tracked in the project to ensure testing coverage doesn't accidently go down with new updates. All new code that is published in the repository should contain tests - coverage.io will help to ensure sportsreference keeps its high test coverage.
> Support coverage.io

- docs/nfl.rst
- sportsreference/nfl/boxscore.py
The team at sports-reference.com changed the abbreviation used for the Houston Texans in all of the NFL's pages from 'HOU' to 'HTX'. When attempting to retrieve data from the Texans using 'HOU', an error will be thrown indicating that there is no data to collect. To reflect this change, all of the documentation that mentioned 'HOU' in the NFL modules should be updated to 'HTX'.
Fixes #160
> Update Houston Texan's abbreviation

- sportsreference/nba/constants.py
After the summer 2019 NBA draft and transfer window, a couple of new players became the first ever players to represent their country in the NBA. As a result, support for their countries was not included yet, preventing sportsreference from pulling stats from these players without throwing errors. With support added, all NBA teams can now be pulled with every roster able to be analyzed.
Fixes #167
> Add support for additional NBA nationalities

- sportsreference/mlb/schedule.py
- sportsreference/mlb/teams.py
- sportsreference/nba/schedule.py
- sportsreference/nba/teams.py
- sportsreference/ncaab/schedule.py
- sportsreference/ncaab/teams.py
- sportsreference/ncaaf/schedule.py
- sportsreference/ncaaf/teams.py
- sportsreference/nfl/schedule.py
- sportsreference/nfl/teams.py
- sportsreference/nhl/schedule.py
- sportsreference/nhl/teams.py
- sportsreference/utils.py
- tests/integration/schedule/test_mlb_schedule.py
- tests/integration/schedule/test_nba_schedule.py
- tests/integration/schedule/test_ncaab_schedule.py
- tests/integration/schedule/test_ncaaf_schedule.py
- tests/integration/schedule/test_nfl_schedule.py
- tests/integration/schedule/test_nhl_schedule.py
- tests/integration/teams/test_mlb_integration.py
- tests/integration/teams/test_nba_integration.py
- tests/integration/teams/test_ncaab_integration.py
- tests/integration/teams/test_ncaaf_integration.py
- tests/integration/teams/test_nfl_integration.py
- tests/integration/teams/test_nhl_integration.py
- tests/unit/test_utils.py
Occasionally, such as right before the beginning of a season, a page will return a valid response but will have no data outside of the default HTML and CSS template. With no data present on the page, `sportsreference` can't parse any information and should indicate the lack of data and return safely.
Fixes #164
> Fix issue retrieving data from empty pages

- sportsreference/ncaaf/boxscore.py
- sportsreference/ncaaf/player.py
- sportsreference/ncaaf/roster.py
The `passing_yards` attribute was missing for NCAAF players that were retrieved from the Roster module. A link to `passing_yards` was misplaced and it should have been included in the `AbstractPlayer` class to ensure it was available everywhere the `AbstractPlayer` class was inherited. With the property added to the `AbstractPlayer` class, it is now accessible in the Roster module.
Fixes #158 
> Add passing_yards to NCAAF players

- sportsreference/ncaab/schedule.py
- tests/unit/test_ncaab_schedule.py
A few NCAAB games are posted on www.sports-reference.com without a listed game start time. In this scenario, the Game class will throw an error attempting to parse the time and create a datetime for the game. In the case a game doesn't include a time, a default of 7:00PM should be used as it tends to be a common start time for NCAAB games.
Fixes #116
> Fix issue parsing NCAAB games without times

- sportsreference/ncaab/roster.py
A few links to player pages on www.sports-reference.com are broken which causes errors to be thrown by the LXML parser while attempting to pull them. Since a `ParserError` is thrown by LXML, we can catch the error and return `None` to safely continue with execution.
Fixes #115
> Fix issue pulling broken NCAAB player pages

- sportsreference/ncaaf/conferences.py
- sportsreference/ncaaf/teams.py
- tests/integration/conferences/test_ncaaf_conferences.py
- tests/integration/teams/test_ncaaf_integration.py
Occasionally, a conference page for NCAAF will be an empty document, devoid of any information that can be parsed. When this happens, the `Teams` class throws an error as it relies on getting information from the `Conferences` class to determine which conference each team participates in. Instead of attempting to pull the information from other sources, if a conference page isn't valid, any team that participates in that conference should have a conference attribute of `None` to avoid presenting incorrect information.
Fixes #179
> Fix NCAAF conference class for empty pages

- sportsreference/ncaab/schedule.py
- tests/unit/test_ncaab_schedule.py
In case an NCAAB game doesn't have a time value associated with it, the default time should be set to midnight instead of 7:00PM as users should have the option on how to handle missing data instead of providing false information. Now, users can check if the `time` property is empty and determine how they want to treat the data in such cases.
> Set default NCAAB time to midnight

- sportsreference/ncaaf/boxscore.py
For games that are yet to occur which are listed in an NCAAF team's schedule, an error will be thrown while attempting to parse a score for the game when none exists. To circumvent this issue, not only should the points be checked if they are `None`, they should also be checked if they are empty.
Fixes #184
> Fix issue with boxscores throwing errors

- tests/integration/boxscore/test_nba_boxscore.py
The NBA Boxscore integration tests randomly started failing while attempting to create an instance of the Boxscore class. The issue is now resolved, allowing the tests to complete as expected again.
Fixes #200
> Fix NBA Boxscore integration tests

- sportsreference/nba/constants.py
With the addition of Christ Koumadje to the NBA, Chad is now a nation that is represented and should be supported by the project.
Fixes #167 
> Support NBA players from Chad

- sportsreference/nba/constants.py
The NBA Boxscores module contains an issue where both the home and away points will return just the away team's points. The HTML has changed on the website in a way that multiple scores are returned instead of just a singular score for home and away, throwing the indexing off for selecting the home team's points. Selecting the final index for the home team's points total works in the case that multiple instances are used for the score.
Fixes #207
> Fix identical home and away scores in NBA Boxscore

- .github/workflows/exhaustive.yml
- .github/workflows/pushtests.yml
- tests/exhaustive/test_mlb.py
- tests/exhaustive/test_nba.py
- tests/exhaustive/test_ncaab.py
- tests/exhaustive/test_ncaaf.py
- tests/exhaustive/test_nfl.py
- tests/exhaustive/test_nhl.py
The exhaustive test suite is currently trying to run duplicate jobs and is failing as a result. No duplicates should be run, and the code should test all requested platforms and versions.
Fixes #214
> Fix issues running duplicate exhaustive tests

- sportsreference/mlb/constants.py
Jesus Luzardo becomes the first MLB player from Peru. As a result, support should be added for Peru in the list of nationalities.
Fixes #211
> Add support for Peru in MLB

- sportsreference/ncaab/constants.py
The NCAAB module was throwing unhandled HTTP 301 status codes for all pages, which masked 404 errors in the case of pages not being present, and therefore allowing false positives for pulling data from the website. The 301 codes were being thrown as the server automatically redirects from http:// to https:// for the linked pages, and should therefore default to https:// for the URLs to ensure proper codes are always returned while pulling webpages.
Fixes #215
> Fix HTTP redirect issues in NCAAB module

- sportsreference/nfl/boxscore.py
For games that are yet to occur which are listed in an NFL team's schedule, an error will be thrown while attempting to parse a score for the game when none exists. To circumvent this issue, not only should the points be checked if they are `None`, they should also be checked if they are empty.
Fixes #219
> Fix issue with future NFL boxscore errors

- sportsreference/nba/roster.py
- tests/unit/test_nba_roster.py
Some players don't have a personal stats page created for them yet, but contain a valid link on roster pages. As implemented, the Roster module for the NBA does not check if the returned data from the page is empty, and will attempt to parse information from an object which is `None`. Instead, if a player's page is invalid, the module should fail-fast and return `None` for the player instead of attempting to parse information or handle other scenarios.
Fixes #217
> Resolve errors while pulling empty NBA stats pages

- sportsreference/nba/boxscore.py
While searching older NBA boxscores, the players lists will sometimes appear empty as the package is unable to pull the boxscore tables on the requested page. The table ID's have been changed in some cases from being pre-fixed with 'box_' to 'box-'. As a result, both prefixes should be checked while attempting to pull relevant tables.
Fixes #222
> Fix missing players for legacy NBA boxscores

- sportsreference/nba/roster.py
- tests/integration/roster/test_nba_roster.py
Occasionally, some NBA roster pages will include empty rows in the roster table, causing the code to think another player exists when one doesn't, throwing an error when it is unable to parse a player ID. If an empty row is ever encountered, it should just be skipped as no information can be parsed anyway.
Fixes #226
> Fix issue pulling empty NBA roster fields

- .github/workflows/pushtests.yml
The checks run by GitHub Actions are only triggered when a branch is pushed to the parent (non-fork) repository, but don't run when a PR is created. This is an issue when anyone creates a PR based on a fork they have created, preventing any collaborators from having their code reviewed automatically.
Fixes #252
> Trigger actions on Pull Requests

- sportsreference/nfl/constants.py
PFF's season page moved to a new URL. Updating `SEASON_PAGE_URL` in `nfl.constants` to reflect the change.
> Update NFL season URL

- sportsreference/constants.py
- sportsreference/nfl/schedule.py
- tests/unit/test_nfl_schedule.py
1. Add a constant `TIE` to represent NFL games that can end in a tie, at the end of overtime.
2. in `schedule.Game.result`, consider all possible outcomes of an NFL game, instead of returning WIN indiscriminately if the if-statement does not evaluate to true. Check whether the result is l/w/t and return the corresponding constant. If none of the above match, return None
`closes #245`
> nfl.schedule.Game.result return win/loss/tie/unknown correctly

- sportsreference/nba/boxscore.py
- sportsreference/nba/constants.py
- sportsreference/utils.py
The NBA Boxscore class was pulling the incorrect home record in some scenarios. Instead of picking a particular index, the home team's record should be the final index as a non-deterministic amount of records could be displayed on a page, but the home team will always be last.
Fixes #230
> Fix incorrect home records in NBA boxscores

- tests/exhaustive/mlb_tests.py
- tests/exhaustive/nba_tests.py
The exhaustive tests are throwing errors on the Windows tests when it tries to parse players that have accents in their names. To prevent the errors from being thrown and the tests from failing, this should be caught and handled properly.
Fixes #259
> Fix encoding issues with player names in tests

- .github/workflows/pushtests.yml
The push tests in GitHub Actions was setting a limit on the maximum number of jobs that can be run in parallel. This becomes an issue when a large number of jobs are spawned concurrently, and makes updates much slower than necessary.
Fixes #272
> Remove limit on parallel jobs

- .github/workflows/exhaustive.yml
- .github/workflows/pushtests.yml
- setup.py
Now that Python 3.8 is generally available, support should be added for the newest version.
Closes #277
> Support Python 3.8

- sportsreference/ncaaf/boxscore.py
- sportsreference/ncaaf/constants.py
- tests/integration/boxscore/test_ncaaf_boxscore.py
- tests/unit/test_ncaaf_boxscore.py
A game summary including a quarter-by-quarter score should be included as an attribute to the NCAAF Boxscores class, which returns a dictionary of both the home and away team's score per quarter, including any overtime results.
Closes #225
> Add game summary for NCAAF boxscores

- sportsreference/nfl/boxscore.py
- sportsreference/nfl/constants.py
- tests/integration/boxscore/test_nfl_boxscore.py
- tests/unit/test_nfl_boxscore.py
A game summary including a quarter-by-quarter score should be included as an attribute to the NFL Boxscores class, which returns a dictionary of both the home and away team's score per quarter, including any overtime results.
Closes #286
> Add game summary for NFL boxscores

- sportsreference/nba/boxscore.py
- sportsreference/nba/constants.py
- tests/integration/boxscore/test_nba_boxscore.py
- tests/unit/test_nba_boxscore.py
A game summary including a quarter-by-quarter score should be included as an attribute to the NBA Boxscores class, which returns a dictionary of both the home and away team's score per quarter, including any overtime results.
Closes #302
> Add game summary for NBA boxscores

- sportsreference/ncaab/boxscore.py
- sportsreference/ncaab/constants.py
- tests/integration/boxscore/test_ncaab_boxscore.py
- tests/unit/test_ncaab_boxscore.py
A game summary including a half-by-half score should be included as an attribute to the NCAAB Boxscores class, which returns a dictionary of both the home and away team's score per half, including any overtime results.
Fixes #304 
> Add game summary for NCAAB boxscores

- sportsreference/mlb/boxscore.py
- sportsreference/mlb/constants.py
- tests/integration/boxscore/test_mlb_boxscore.py
- tests/unit/test_mlb_boxscore.py
A game summary including a inning-by-inning score should be included as an attribute to the MLB Boxscores class, which returns a dictionary of both the home and away team's score per half, including any extra inning results.
Closes #306
> Add game summary for MLB boxscores

- sportsreference/nfl/constants.py
- sportsreference/nfl/teams.py
- tests/integration/teams/test_nfl_integration.py
A new property is added which indicates how far an NFL team made it in the post-season, if at all. This allows quick queries to see if the team made it to a particular round, or if they won or lost one of the playoff games.
Fixes #242
> Add post-season result for NFL teams

- sportsreference/ncaab/roster.py
- tests/unit/test_ncaab_roster.py
Occasionally, some NCAAB players will not have a weight listed on their stats page on sports-reference.com. This will return `None` for the property in the Player class. While attempting to parse the weight from None, an error will be thrown. Doing a simple check to see if the weight is valid prior to parsing will resolve the issue and allow execution as expected.
Fixes #298
> Fix issue pulling missing NCAAB player weight

- sportsreference/nba/roster.py
Occasionally, an NBA team's roster page on sports-reference.com will be empty, causing an error to be thrown while attempting to parse the page. Adding an additional check to see if the page is parsable will gracefully handle situations where the page is invalid.
Fixes #337
> Fix issue pulling empty NBA roster page

- sportsreference/ncaaf/roster.py
For a handful of NCAAF players, the "Receiving & Rushing" table has an ID of `receiving` instead of the commonly-used `rushing`. The former was not being parsed, and the relevant stats were ignored for those players. Simply adding that ID to the list of tables to parse resolves the issue.
Fixes #362
> Add NCAAF player receiving stats

- sportsreference/ncaab/teams.py
- tests/integration/teams/test_ncaab_integration.py
In 2010 and earlier years, some NCAAB teams, such as Bryant University, made the transition from Division-II or lower to Division-I basketball. This caused an issue on the website as sometimes those teams would be displayed in the overall school stats, but they would not have their own standalone stats page specific to their school. This would prevent the code from parsing the team's conference and other stats, and would throw an error while attempting to instantiate the team. Doing a simple check to see if the team exists in the conference dataset prior to checking instantiating the team mitigates this issue.
Fixes #365
> Skip NCAAB teams without stat pages

- sportsreference/mlb/boxscore.py
The BoxscorePlayer class for MLB currently forces the number of innings pitched per player to be an integer, truncating any partial innings they might have played. This makes the data incomplete and unreliable. Allowing the number of innings pitched to be a float will now indicate partial innings pitched, with results ending in '.1' or '.2' to indicate one third or two thirds of an inning pitched, respectively.
Fixes #295
> Convert MLB innings pitched to float

- sportsreference/mlb/boxscore.py
The home and away players in the MLB Boxscore class were being saved in the opposite property, causing home players to show under away_players and vice-versa. The algorithm wrongly assumed the away team matched with odd-numbered tables, when the numbers are zero-based, and should instead match with even-numbered tables as a result.
Fixes #368
> Switch MLB Boxscore player teams

- sportsreference/nfl/roster.py
Certain NFL rosters contain links to individual player pages that are either invalid or incomplete, causing an error during the parsing step. This occurs more frequently with earlier seasons as many pages were invalid. Simply checking if a page is invalid prior to attempting to parse the information will prevent the error from being thrown, and allow expected execution to continue.
Fixes #376
> Fix issue pulling NFL rosters

- sportsreference/nfl/schedule.py
For NFL teams that played in playoff games which took place after the New Year, the `datetime` in the schedule would be incorrect as it would use the default year instead of the actual year the game was played. Checking if the game was played in the first couple months of the year and incrementing the year by 1 if so resolves this issue as games being played in January or February of the same season are in a different calendar year.
Fixes #375
> Fix NFL datetimes for playoff games

- sportsreference/fb/roster.py
- sportsreference/fb/schedule.py
- sportsreference/fb/team.py
- tests/unit/test_fb_roster.py
- tests/unit/test_fb_schedule.py
- tests/unit/test_fb_team.py
The website will occasionally throw HTTP errors for various reasons, ranging from gateway timeouts, to invalid pages, to invalid syntax. Regardless of the cause, any of these issues makes parsing pages
impossible, and should therefore be skipped.
Fixes #379
> Handle football HTTP errors

- sportsreference/ncaaf/player.py
- sportsreference/ncaaf/roster.py
- tests/integration/roster/ncaaf/jd-dillinger-1.html
- tests/integration/roster/test_ncaaf_roster.py
Fixes #373
Adds kicking stats (attempts and percentage) to NCAAF players.
Not sure how the previous PR #374  broke but here it is again?
> add kicking stats to ncaaf players

- .github/workflows/pushtests.yml
Instead of publishing universal wheels which support both Python 2 and Python 3, only Python 3-specific wheels should be built and published as this package no longer support Python 2.
Fixes #387 
> Remove universal wheels

- sportsreference/fb/team.py
- tests/unit/test_fb_team.py
If the Team class for football is unable to pull a team's page, the document for the team will be invalid, and the '_doc' attribute will not exist for that team. While trying to pull the schedule or roster for that team, an error will be thrown that the '_doc' attribute does not
exist.
Simply checking if the attribute exists, and setting it to `None` if not will allow the Schedule and Roster modules to retry pulling the page again to see if it works.
Fixes #391 
> Fix issue pulling football schedules and rosters

- .github/workflows/pushtests.yml
The original version of Codecov used in the repository required a token for proper authentication, which worked fine for all non-fork updates to the repository as the GitHub action secret was saved and usable. For all forked updates, however, the secret was not saved, and all actions would
fail as Codecov would try and push the coverage report without a token.
With the latest release of Codecov action v1.0.6, tokenless pushing is now available which solves the problem of pushing from forked repositories.
> Use tokenless Codecov action

- sportsreference/ncaaf/player.py
- sportsreference/ncaaf/roster.py
- tests/unit/test_ncaaf_boxscore.py
- tests/unit/test_ncaaf_roster.py
The NCAAF module has deprecated the `attempted_passes` property in favor of `pass_attempts` to be more consistent with other modules as well as the naming convention already present in NCAAF.
Fixes #171
> Remove attempted_passes from NCAAF

- sportsreference/nfl/boxscore.py
- tests/integration/boxscore/test_nfl_boxscore.py
- tests/unit/test_nfl_boxscore.py
The NFL boxscores class needs a datetime property comprised of both the date and time of the game to allow easier referencing of games in a schedule.
Fixes #384
> Add datetime property to NFL boxscores

- sportsreference/mlb/roster.py
- sportsreference/nba/roster.py
- sportsreference/nfl/roster.py
- sportsreference/nhl/roster.py
- tests/unit/test_mlb_roster.py
- tests/unit/test_nba_roster.py
- tests/unit/test_nfl_roster.py
- tests/unit/test_nhl_roster.py
If a player doesn't have a weight listed on his/her page, an `AttributeError` will be thrown while trying to call `replace` on an object of `None`. Simply checking if the weight is valid prior to attempting to replace the unit will prevent this error.
Fixes #393 
> Handle missing player weights throwing errors

- sportsreference/nba/boxscore.py
- sportsreference/nba/roster.py
- tests/unit/test_nba_boxscore.py
This small PR simply adds some exception handling to some of the calculations for the NBA boxscore classes. 
I also intend to do this for the other classes as well. 
This was done because in the current state, running something like the following would raise a `TypeError`: 
```python
from sportsreference.nba.boxscore import Boxscore
bs = Boxscore('194910290TRI')
df = bs.dataframe
```
This was because the information that would have been required for all of these operations were valued None. While the decorators handle this issue for the particular values, the `TypeError` would happen with the arithmetic operators. 
This assumes that the attributes will only be of the correct type (float or int) or NoneType. 
This should also be done for the other classes. It appears that this will be a …
> NBA: adding TypeError checks around operations

- docs/nba.rst
- sportsreference/nba/nba_utils.py
- sportsreference/nba/teams.py
- tests/integration/teams/test_nba_integration.py
Instead of requiring users to go through the Teams class to get a specific team, the NBA modules now enable a specific team to be directly queried by using the Team class. This reduces computational complexity by removing the need to instantiate every team while also making it more intuitive for users.
Related to #360 
> Enable NBA Team to be directly accessible

- tests/integration/schedule/test_fb_schedule.py
Using the current datetime could run into an issue for the football schedule tests if the date a test was run happened to be an actual date on the team's schedule would fail to throw a `ValueError`. Instead, a date that is known to not be on the team's schedule should be used to ensure
the tests can complete regardless of the date run.
Fixes #408 
> Fix issue with FB schedule using invalid date

- docs/mlb.rst
- sportsreference/mlb/mlb_utils.py
- sportsreference/mlb/teams.py
- tests/integration/teams/test_mlb_integration.py
Instead of requiring users to go through the Teams class to get a specific team, the MLB modules now enable a specific team to be directly queried by using the Team class. This reduces computational complexity by removing the need to instantiate every team while also making it more intuitive for users.
> Enable MLB Team to be directly accessible

- docs/ncaab.rst
- sportsreference/ncaab/ncaab_utils.py
- sportsreference/ncaab/teams.py
- tests/integration/teams/test_ncaab_integration.py
Instead of requiring users to go through the Teams class to get a specific team, the NCAAB modules now enable a specific team to be directly queried by using the Team class. This reduces computational complexity by removing the need to instantiate every team while also
making it more intuitive for users.
> Enable NCAAB Team to be directly accessible

- docs/ncaaf.rst
- sportsreference/ncaaf/ncaaf_utils.py
- sportsreference/ncaaf/teams.py
- tests/integration/roster/test_ncaaf_roster.py
- tests/integration/teams/test_ncaaf_integration.py
Instead of requiring users to go through the Teams class to get a specific team, the NCAAF modules now enable a specific team to be directly queried by using the Team class. This reduces computational complexity by removing the need to instantiate every team while also
making it more intuitive for users.
> Enable NCAAF Team to be directly accessible

- docs/nfl.rst
- sportsreference/nfl/nfl_utils.py
- sportsreference/nfl/teams.py
- tests/integration/roster/test_nfl_roster.py
- tests/integration/teams/test_nfl_integration.py
Instead of requiring users to go through the Teams class to get a specific team, the NFL modules now enable a specific team to be directly queried by using the Team class. This reduces computational complexity by removing the need to instantiate every team while also making it more intuitive for users.
> Enable NFL Team to be directly accessible

- docs/nhl.rst
- sportsreference/nhl/nhl_utils.py
- sportsreference/nhl/teams.py
- tests/integration/roster/test_nhl_roster.py
- tests/integration/teams/test_nhl_integration.py
Instead of requiring users to go through the Teams class to get a specific team, the NHL modules now enable a specific team to be directly queried by using the Team class. This reduces computational complexity by removing the need to instantiate every team while also making it more intuitive for users.
> Enable NHL Team to be directly accessible

- .github/workflows/exhaustive.yml
- .github/workflows/pushtests.yml
- setup.py
With Python 3.5 reaching its end-of-life date on September 13, 2020, sportsreference should officially drop support for Python 3.5 to encourage users to migrate to a newer version of Python that remain supported in the future. Only issues for Python 2.7 that pose serious security risks will be fixed in the future and only on a case-by-case basis.
Fixes #372
> Drop support for Python 3.5

- .github/workflows/pushtests.yml
The previous version of Codecov in the Actions was not authenticating properly with the Codecov servers, preventing the coverage diffs from being displayed in PRs. By updating to the latest versions of Python and Codecov, the coverage reports will now be displayed on PR.
Fixes #473
> Update Codecov to latest version

- sportsreference/nba/constants.py
- sportsreference/nba/roster.py
- tests/integration/roster/test_nba_roster.py
In addition to the overall career and season stats for NBA players, stats per 100 possessions should also be included to represent each player's efficiency while on the court. This is especially crucial to compare players that might have vastly differing amounts of playtime.
Fixes #257
> Add Per 100 Possessions stats to NBA

- sportsreference/nba/nba_utils.py
- sportsreference/nba/roster.py
- sportsreference/nba/schedule.py
- tests/integration/schedule/test_nba_schedule.py
- tests/unit/test_nba_utils.py
Given the lengthy delays to the NBA season in 2020, attempting to pull the NBA modules towards the end of the calendar year throws off the logic as the default logic assumes the next season is either getting ready to start or is already underway. In 2020, however, this has not yet happened, and an `HTTPError` will be thrown while attempting to pull the stats without specifying the year. By doing a one-off check for 2020, a handler can be made to identify whether or not the next season has started yet. This will only be applicable for the second half of 2020, and can be removed at a later date.
Fixes #464 
> Fix issues pulling default NBA year for 2020

- sportsreference/mlb/boxscore.py
- sportsreference/nba/boxscore.py
- sportsreference/nfl/boxscore.py
- sportsreference/nhl/boxscore.py
Newer versions of `pycodestyle` flag inadequate variable names, such as single letters, which should be replaced with more descriptive names.
Fixes #485
> Replace invalid variable name in Boxscore modules

- sportsreference/fb/team.py
- sportsreference/mlb/mlb_utils.py
- sportsreference/mlb/teams.py
- sportsreference/nba/nba_utils.py
- sportsreference/nba/teams.py
- sportsreference/ncaab/ncaab_utils.py
- sportsreference/ncaab/teams.py
- sportsreference/ncaaf/ncaaf_utils.py
- sportsreference/ncaaf/teams.py
- sportsreference/nfl/nfl_utils.py
- sportsreference/nfl/teams.py
- sportsreference/nhl/nhl_utils.py
- sportsreference/nhl/teams.py
- sportsreference/utils.py
- tests/unit/test_utils.py
To reduce server load on sports-reference.com, users should be allowed to pass local data files which are cached versions of the webpages to the classes. This also enables users to work offline without relying on the website for a connection.
Fixes #9
> Allow local data files over downloading pages

- sportsreference/nba/boxscore.py
The NBA Boxscores were showing no game summaries for the per-quarter scores for both teams. It appears sports-reference.com was updated to include a space in the class attribute for the game summary table, throwing off the parser.
Fixes #455
> Fix NBA Boxscore summary

- sportsreference/nfl/boxscore.py
- sportsreference/nfl/constants.py
- tests/unit/test_nfl_boxscore.py
Occasionally, some NFL Boxscores would incorrectly list the home team players as away. This is caused by the home and away teams using different abbreviations in their URIs than the abbreviations listed in the tables, which would fail the branching logic to select the players for a specific team.
By checking the abbreviations listed on the actual page outside of the URIs, the players can be placed properly into one team or the other.
Fixes #501
> Fix NFL players wrongly being listed as away

- sportsreference/nba/player.py
- sportsreference/nba/roster.py
In cases where no information is present for an NBA player, the default value of `None` should be used for all attributes. At present, the code was unable to initialize many default common variables for players, which resulted in an error while trying to pull data from the `Roster` class.
Fixes #456
> Update default values for NBA players

- tests/integration/roster/test_ncaaf_roster.py
The NCAAF tests were pulling data from the website for certain players instead of the local test files.
> Fix issue with NCAAF tests

- sportsreference/mlb/constants.py
- sportsreference/mlb/roster.py
- sportsreference/nba/constants.py
- sportsreference/nba/nba_utils.py
- sportsreference/nba/roster.py
- sportsreference/ncaab/constants.py
- sportsreference/ncaab/roster.py
- sportsreference/ncaaf/constants.py
- sportsreference/ncaaf/roster.py
- sportsreference/nfl/constants.py
- sportsreference/nfl/roster.py
- sportsreference/nhl/constants.py
- sportsreference/nhl/roster.py
- tests/integration/roster/test_mlb_roster.py
- tests/integration/roster/test_nba_roster.py
- tests/integration/roster/test_ncaab_roster.py
- tests/integration/roster/test_ncaaf_roster.py
- tests/integration/roster/test_nfl_roster.py
- tests/integration/roster/test_nhl_roster.py
The coach or manager's full name is now a property that can be retrieved from a team's Roster class.
Closes #285
> Add coach to Roster

- sportsreference/fb/team.py
- tests/unit/test_fb_team.py
Occasionally, a team's league position will not be posted on their team page, throwing an error while attempting to parse that information. Defaulting the value to `None` in this scenario will skip the error while allowing expected functionality to continue.
Fixes #530 
> Fix issue pulling football league positions

- sportsreference/nfl/boxscore.py
- tests/unit/test_nfl_boxscore.py
For NFL games that are scheduled but have not yet taken place, the code would take the preview link for the game and treat it as the Boxscore link, causing errors to be thrown while attempt to pull Boxscore data from the preview which doesn't have the intended information.
Fixes #531 
> Fix issue pulling future NFL boxscores

- sportsreference/utils.py
If the code throws a 301 redirect error which leads to a 404 error, it will be treated as the request returning a valid result, when that shouldn't be the case. By pulling the page on a status code of 301, the final value is returned for the `status_code`, which in the case of a 404 error, will return the intended value.
Fixes #533 
> Handle redirects to 404 errors

- sportsreference/fb/squad_ids.py
Some teams had the incorrect squad IDs in the football section, making it appear they didn't exist.
Fixes #515 
> Fix incorrect squad IDs for football

- tests/exhaustive/fb_tests.py
Some player names fail to encode in the exhaustive Windows tests, causing the test to fail. Forcing UTF-8 encoding allows the tests to continue as expected.
Fixes #537 
> Encode FB player names in exhaustive tests

- tests/exhaustive/ncaab_tests.py
Windows is unable to handle certain NCAAB player names in the exhaustive tests, and need to be specially handled.
> Encode NCAAB player names

- tests/exhaustive/fb_tests.py
A few squad names are unable to be properly encoded on Windows for the exhaustive football tests and need to be specially handled.
> Encode exhaustive football tests

- .github/workflows/pushtests.yml
- requirements.txt
By increasing the number of workers available for pytest, the testing can complete faster for better turnarounds.
> Increase testing workers

- sportsipy/nba/nba_utils.py
- tests/integration/teams/nba_stats/NBA_2021.html
- tests/integration/teams/test_nba_integration.py
The NBA Teams module was attempting to pull stats from a table that doesn't exist as the tables have been renamed on the website.
Fixes #626
> Fix issue pulling NBA stats

- tests/unit/test_nba_utils.py
Given the format of the NBA pages changed on the website, the unit tests need to be updated to pull the default year for 2020 given the scheduling is different for that year.
> Fix issue pulling default year for NBA

- tests/integration/teams/test_mlb_integration.py
The MLB teams test wasn't pulling the saved HTML file and was instead pulling directly from the sports-reference.com website which resulted in non-deterministic behavior.
> Fix issue with the MLB test

- sportsipy/nfl/roster.py
Currently, when trying to get the roster for a given NFL team, the
result is an empty list. The reason for this is because the html element
that is being used to search within the roster html page is incorrect.
When changing that element to an element that exists on the page, we get
the correct results for an NFL roster.
Example: 
roster = Roster("WAS")
print(roster)
["Kendall Fuller", ...]
Signed-Off-By: Alec Keller <alec.keller.17@gmail.com>
closes #677
> Fix empty NFL Rosters

- .github/workflows/exhaustive.yml
- .github/workflows/pushtests.yml
- setup.py
Python 3.6 is no longer supported by the community and should be dropped from this repository.
Closes #701
> Drop support for Python 3.6

- requirements.txt
The updated version of numpy is incompatible with Python 3.7 and causes tests with that Python version to fail. Reverting to the latest version supported by Python 3.7 resolves the issue.
> Revert numpy version for Python 3.7 support

- .github/workflows/pushtests.yml
The windows-2016 OS is deprecated on GitHub Actions and will automatically be cancelled for any jobs that are run against it.
> Remove windows-2016 OS from GitHub Actions
